strategy:
  instruments:
  - TEST-EQ
  timeframe: 1m
  ema_short: 10
  ema_long: 22
  supertrend_period: 11
  supertrend_multiplier: 3.5
  atr_period: 11
risk:
  risk_per_trade_percent: 0.25
  max_daily_loss_percent: 3.0
  consecutive_losses_stop: 3
  trailing_stop:
    activate_at_atr: 0.5
    trail_by_atr: 0.3
  take_profit_atr: 0.6
  volatility_adjustment:
    high_vol_threshold_percent: 0.5
    risk_reduction_factor: 0.5
trading:
  hours:
    start: 09:15
    end: '15:20'
  paper_trading: true
cooldown:
  after_consecutive_losses_minutes: 30
