strategy:
  trade_indices:
  - BANKNIFTY
  - NIFTY
  - FINNIFTY
  instrument_types:
  - OPTIDX
  timeframe: 1m
  # Options-specific parameters
  strike_selection:
    atm_range: 2  # +/- strikes from ATM
    prefer_otm: true
    min_premium: 5.0
    max_premium: 200.0
  expiry_preference:
    max_days_to_expiry: 7
  # Optimized scalping indicators for high win rate
  ema_short: 5
  ema_long: 13
  supertrend_period: 7
  supertrend_multiplier: 2.5
  atr_period: 14
  min_confirmations: 9  # Higher for better accuracy
  rsi_period: 5
  bb_period: 20
  stoch_k: 5
  stoch_d: 3
  volume_surge_threshold: 1.5  # More sensitive
  min_volatility: 0.5
  max_volatility: 3.0
  # Options Greeks thresholds
  min_delta: 0.3
  max_delta: 0.8
  max_theta: -0.5
  min_gamma: 0.01
  # NEW: Scalping score weights
  scoring_weights:
    delta_multiplier: 100
    gamma_multiplier: 10000
    theta_base: 10
    premium_target: 50
    premium_divisor: 10
    moneyness_divisor: 100
  # NEW: Scalping thresholds for high profits
  scalping_thresholds:
    momentum: 0.15
    max_trade_hold_minutes: 8  # Faster exits
risk:
  risk_per_trade_percent: 1.2  # Higher for more profits
  max_daily_loss_percent: 3.0
  consecutive_losses_stop: 3  # Stricter
  max_positions: 3  # Focus on quality
  # Options-specific risk parameters
  max_premium_risk_percent: 2.0
  theta_decay_exit_minutes: 15
  theta_decay_min_profit: 10
  quick_profit_threshold: 25
  quick_profit_min_time: 2
  iv_spike_threshold: 20.0
  trailing_stop:
    activate_at_profit_percent: 25
    trail_by_percent: 15
  take_profit_percent: 60  # Higher profits
  stop_loss_percent: 35  # Tighter stops
  volatility_adjustment:
    high_vol_threshold_percent: 1.2
    risk_reduction_factor: 0.5
trading:
  hours:
    start: 09:15
    end: '15:20'
  # Options scalping optimal sessions
  high_volume_sessions:
    - start: '09:15'
      end: '10:30'
    - start: '14:30'
      end: '15:15'
  avoid_sessions:
    - start: '12:00'
      end: '13:00'  # Lunch break low volume
  paper_trading: false  # Live trading for options
  square_off_time: '15:10'  # Square off before close
  # NEW: Trading parameters
  lot_sizes:
    BANKNIFTY: 15
    NIFTY: 25
    FINNIFTY: 25
  risk_free_rate: 0.065
  default_volatility: 0.18
cooldown:
  after_consecutive_losses_minutes: 20
  after_big_loss_minutes: 45
  big_loss_threshold_percent: 1.5
network:
  retry_attempts: 3
  retry_delay_seconds: 2