strategy:
  instruments:
  - NIFTYBEES-EQ
  - BANKBEES-EQ
  - RELIANCE-EQ
  timeframe: 1m
  ema_short: 8
  ema_long: 21
  supertrend_period: 10
  supertrend_multiplier: 2.8
  atr_period: 14
risk:
  risk_per_trade_percent: 0.4
  max_daily_loss_percent: 2.5
  consecutive_losses_stop: 4
  trailing_stop:
    activate_at_atr: 0.3
    trail_by_atr: 0.4
  take_profit_atr: 1.0
  volatility_adjustment:
    high_vol_threshold_percent: 0.8
    risk_reduction_factor: 0.6
trading:
  hours:
    start: 09:15
    end: '15:20'
  paper_trading: true
cooldown:
  after_consecutive_losses_minutes: 30
