strategy:
  trade_indices:
  - BANKNIFTY
  instrument_types:
  - OPTIDX
  timeframe: 1m
  ema_short: 10
  ema_long: 22
  supertrend_period: 11
  supertrend_multiplier: 3.5
  atr_period: 11
  min_confirmations: 7
  rsi_period: 7
  bb_period: 20
  stoch_k: 5
  stoch_d: 3
  volume_surge_threshold: 1.5
  min_volatility: 0.3
  max_volatility: 2.0
risk:
  risk_per_trade_percent: 0.4
  max_daily_loss_percent: 2.5
  consecutive_losses_stop: 4
  trailing_stop:
    activate_at_atr: 0.3
    trail_by_atr: 0.4
  take_profit_atr: 1.0
  volatility_adjustment:
    high_vol_threshold_percent: 0.8
    risk_reduction_factor: 0.6
trading:
  hours:
    start: 09:15
    end: '15:20'
  paper_trading: true
cooldown:
  after_consecutive_losses_minutes: 30
