# Strategy Configuration
strategy:
  instruments:
    - "NIFTYBEES-EQ"
    - "BANKBEES-EQ"
  timeframe: "1minute"
  ema_short: 9
  ema_long: 21
  supertrend_period: 10
  supertrend_multiplier: 3
  atr_period: 14
  trailing_sl:
    is_enabled: true
    percentage: 0.5 # 0.5%

# Risk Management Configuration
risk:
  risk_per_trade_percent: 0.25
  max_daily_loss_percent: 3.0
  consecutive_losses_stop: 3

# Trading Session Configuration
trading:
  hours:
    start: "09:15"
    end: "15:20"
    end_of_day_exit: "15:15" # Close all positions at this time

# Cooldown Configuration
cooldown:
  after_consecutive_losses_minutes: 30
