version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app # Mount the app directory for live reloading
      - ./data:/app/data # Mount a volume for the SQLite database
      - ./logs:/app/logs # Mount a volume for logs
    env_file:
      - .env
    restart: unless-stopped

volumes:
  data:
  logs:
